User directories
NickvisionApps/Aura pull request #14
Opened 2023-09-01 20:57 UTC by fsobolev

Marking this as draft because I didn't test anything yet (will do tomorrow), although the lib builds and so I hope the code is done.

`UserDirectories` is a class allowing to get paths for various user folders. Unlike `Environment.SpecialFolder` it's more Linux-oriented, but should work on Windows too.

| Name | Linux | Windows |
| --- | --- | --- |
| Home | `$HOME`; `/home/{UserName}` | `SpecialFolder.Personal` |
| Config | `$XDG_CONFIG_HOME`; `{Home}/.config` | `SpecialFolder.ApplicationData` |
| ApplicationConfig | `{Config}/{AppInfo.Name}` | `{Config}\{AppInfo.Name}` |
| Cache | `$XDG_CACHE_HOME`; `{Home}/.cache` | `SpecialFolder.LocalApplicationData`<sup>[1]</sup> |
| ApplicationCache | `{Cache}/{AppInfo.Name}` | `{Cache}\{AppInfo.Name}` |
| LocalData<sup>[2]</sup> | `$XDG_DATA_HOME`; `{Home}/.local/share` | `SpecialFolder.ApplicationData` |
| ApplicationLocalData | `{LocalData}/{AppInfo.Name}` | `{LocalData}\{AppInfo.Name}` |
| Runtime | `$XDG_RUNTIME_DIR`; `/run/user/$UID` | Exception |
| Desktop | `$XDG_DESKTOP_DIR` (env var first, then the value from config file) | `SpecialFolder.DesktopDirectory`<sup>[3]</sup> |
| Documents | `$XDG_DOCUMENTS_DIR` (env var first, then the value from config file) | `SpecialFolder.MyDocuments` |
| Download | `$XDG_DOWNLOAD_DIR` (env var first, then the value from config file) | Get path using `SHGetKnownFolderPath` from `shell32.dll` |
| Music | `$XDG_MUSIC_DIR` (env var first, then the value from config file) | `SpecialFolder.MyMusic` |
| Pictures | `$XDG_PICTURES_DIR` (env var first, then the value from config file) | `SpecialFolder.MyPictures` |
| PublicShare | `$XDG_PUBLICSHARE_DIR` (env var first, then the value from config file) | `SpecialFolder.CommonDocuments`<sup>[4]</sup> |
| Templates | `$XDG_TEMPLATES_DIR` (env var first, then the value from config file) | `SpecialFolder.Templates` |
| Videos | `$XDG_VIDEOS_DIR` (env var first, then the value from config file) | `SpecialFolder.MyVideos` |

<sup>[1]</sup> LocalApplicationData seems to be what is expected to use for cache and other temporary files on Windows
<sup>[2]</sup> I'm not sure about the name, but I think this is the least confusing
<sup>[3]</sup> I don't fully understand the difference between Desktop and DesktopDirectory in SpecialFolder, but from examples that I found DesktopDirectory seems to be a preferred option
<sup>[4]</sup> I know Common* directories in Windows are not the same as PublicShare in Linux, but I feel it's close enough. And CommonDocuments are used because MyDocuments considered the main user directory on Windows (SpecialFolder.Personal and MyDocuments are the same, there is UserProfile but it's expected to not write anything there).

I also modified ConfigurationLoader. When working on Cavalier I figured out that if the config contains invalid data (double number instead of integer for example), the app just crashes. The changes should prevent this: if JSON failed to deserialize data for whatever reason, an empty json is written to config file, but if the file existed, a backup is created first.

2023-09-02 12:27 UTC, fsobolev commented
More changes:
1. I read how we use Aura in projects and found it a bit confusing that we use Aura constructor that returns an object but then we don't need this object because there's Aura.Active, so I made the constructor private and added static Aura.Init. It will also check that there's only one Aura.
2. Added AuraException to use instead of generic exception.
3. My first time writing tests 😄 It was easier than I thought, heh. Currectly there are tests for Aura initialization and for all UserDirectories (all passing ofc, but I will check everything with real code later today).

2023-09-02 18:39 UTC, fsobolev commented
Tested with Tagger, all I had to do is a small change in MainWindowController:

```
        Aura.Init("org.nickvision.tagger", "Nickvision Tagger", _("Tagger"), _("Tag your music"));
        if (Directory.Exists($"{UserDirectories.Config}{Path.DirectorySeparatorChar}Nickvision{Path.DirectorySeparatorChar}{AppInfo.Name}"))
        {
            // Move config files from older versions and delete old directory
            try
            {
                foreach (var file in Directory.GetFiles($"{UserDirectories.Config}{Path.DirectorySeparatorChar}Nickvision{Path.DirectorySeparatorChar}{AppInfo.Name}"))
                {
                    File.Move(file, $"{UserDirectories.ApplicationConfig}{Path.DirectorySeparatorChar}{Path.GetFileName(file)}");
                }
            }
            catch (IOException) { }
            Directory.Delete($"{UserDirectories.Config}{Path.DirectorySeparatorChar}Nickvision{Path.DirectorySeparatorChar}{AppInfo.Name}", true);
        }
```

Code for moving old config changed because Aura creates `ApplicationConfig` directory in getter (I did this on purpose: if we want to get some older it means we need it to exists), so we can't use `Directory.Move` like we did before.

2023-09-03 02:10 UTC, nlogozzo requested changes
Overall looks really good to me! The tests are super call too!!

Just one minor thing for the`UserDirectories` below. Also, could you maybe make a github action workflow for running the tests?

2023-09-03 02:10 UTC, nlogozzo commented on Nickvision.Aura/UserDirectories.cs
> +        ParseXDGConfig();
Move the code from the method itself here as it's only used here.

2023-09-03 02:10 UTC, nlogozzo commented on Nickvision.Aura.Tests/Aura.Test.cs
> +public class AuraTest
Since the class name is `AuraTest` could name the file `AuraTest.cs` instead of `Aura.Test.cs`

2023-09-03 02:28 UTC, nlogozzo approved these changes

2023-09-03 02:35 UTC, merged